version: '3.2'

services:
  webapp:
    volumes:
      - nfsmount:/var/www/html

volumes:
 nfsmount:
     driver: local
     driver_opts:
       type: nfs
       o: addr=host.docker.internal,rw,lock,hard,nointr,nfsvers=3
       device: ":${PWD}/application/"
