version: '3.2'

services:

  webapp:
    build: .
    volumes:
      - ./application:/var/www/html
    ports:
      - 80:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./application/data/database:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:3
    volumes:
      - ./application/data/cache/:/data
    ports:
      - 6390:6379
