#!/bin/bash

NFS_CONF="/etc/nfs.conf"
NFS_EXPORTS="/etc/exports"
WORKING_DIR=$(pwd)

prepare_nfs()
{
    echo "Checking NFS mounts + permissions"

    local do_restart=0

    # Update NFS config
    if [[ $(grep -c "require_resv_port" "$NFS_CONF") -eq 0 ]]; then
        echo " - Updating config ($NFS_CONF)"
        echo "nfs.server.mount.require_resv_port = 0" | exec sudo tee -a "$NFS_CONF" > /dev/null

        do_restart=1
    fi

    # Fix NFS permission errors
    if [[ $(grep -c "$WORKING_DIR" "$NFS_EXPORTS") -eq 0 ]]; then
        echo " - Updating exports ($NFS_EXPORTS)"
        echo "\"$WORKING_DIR\" localhost -alldirs -mapall=501:20" | exec sudo tee -a "$NFS_EXPORTS" > /dev/null

        do_restart=1
    fi

    if [[ do_restart -eq 1 ]]; then
        echo " - Restarting NFS service"
        exec sudo nfsd restart
    fi
}

main()
{
    prepare_nfs
    docker-compose -f docker-compose.yaml -f docker-compose-osx.yaml restart
}

main
