version: 2
jobs:
  buildAndDeployStage:
    docker:
      - image: registry.gitlab.com/exporo/circleci-stretch-php-cli-node-awscli
        environment:
          MYSQL_HOST: 127.0.0.1
      - image: circleci/mysql:5.7.24
        environment:
          MYSQL_DATABASE: forge
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret

    working_directory: ~/pp
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo 'COMPOSER_CACHE_DIR=$CIRCLE_WORKING_DIRECTORY/cache/composer' >> $BASH_ENV

      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: set nova auth parameter
          command: echo "{\"http-basic\":{\"nova.laravel.com\":{\"username\":\"${NOVA_USERNAME}\",\"password\":\"${NOVA_PASSWORD}\"}}}" > ./application/auth.json

      - run:
          name: Install Yarn
          command: curl -o- -L https://yarnpkg.com/install.sh | bash

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "./application/yarn.lock" }}

      - run:
          name: Install frontend dependencies
          command: cd ./application && yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "./application/yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Build frontend assets
          command: cd application && npm run production

      - restore_cache:
          keys:
            - composer-cache

      - restore_cache:
          keys:
            - vendor-dev-{{ checksum "./application/composer.lock" }}
            - vendor-dev-

      - run:
          name: install dependencies with composer
          command: cd application && composer install --no-progress --no-interaction

      - save_cache:
          key: vendor-dev-{{ checksum "./application/composer.lock" }}
          paths:
            - ./application/vendor

      - run:
          name: run unit tests
          command: cd application && DB_PORT=3306 DB_USERNAME=homestead DB_PASSWORD=secret ./vendor/bin/phpunit --log-junit ~/phpunit/junit.xml

      - store_test_results:
          path: ~/phpunit

      - run:
          name: Lint the project
          command: cd application && composer lint

      - restore_cache:
          keys:
            - vendor-{{ checksum "./application/composer.lock" }}
            - vendor-

      - run:
          name: Remove composer dev-dependencies
          command: cd application && composer install --prefer-dist --no-progress --no-interaction --no-dev --no-suggest --classmap-authoritative

      - save_cache:
          key: composer-cache
          paths:
            - ./cache/composer

      - save_cache:
          key: vendor-{{ checksum "./application/composer.lock" }}
          paths:
            - ./application/vendor

      - run:
          name: Configuring aws cli profile
          command: |
            aws configure set region eu-central-1 --profile pp-admin && \
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile pp-admin && \
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile pp-admin

      - run:
          name: Build and push docker image
          command: cd ./infrastructure && npm install && npm run docker

      - run:
          name: Update aws infrastructure - reload/restart services
          command: cd ./infrastructure && npm run aws

  upsertAndDeployProd:
    docker:
      - image: registry.gitlab.com/exporo/circlecici-stretch-php-cli-node-awscli
    working_directory: ~/pp
    steps:
      - checkout
      - run:
          name: configuring aws cli profile
          command: |
            aws configure set region eu-central-1 --profile pp-admin && \
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile pp-admin && \
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile pp-admin
      - run:
          name: update aws infrastructure - reload/restart services
          command: cd ./infrastructure && npm install && npm run aws-prod

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - buildAndDeployStage:
          filters:
            branches:
              only:
                - stage
      - hold:
          type: approval
          requires:
            - buildAndDeployStage
      - upsertAndDeployProd:
          requires:
            - hold
