version: 2
jobs:
  build:
    docker:
      - image: registry.gitlab.com/exporo/circleci-stretch-php-cli-node-awscli
    working_directory: ~/pp
    steps:
      - run:
          name: Setup Environment Variables
          command: |
            echo 'COMPOSER_CACHE_DIR=$CIRCLE_WORKING_DIRECTORY/cache/composer' >> $BASH_ENV

      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
          keys:
            - composer-cache-{{ .Environment.CIRCLE_SHA1 }}
            - composer-cache-
      - restore_cache:
          keys:
            - vendor-{{ checksum "./application/composer.lock" }}
            - vendor-
      - run:
          name: set nova auth paramter
          command: |
            sed -i \
              -e 's/CI_NOVA_USERNAME/${NOVA_USERNAME}/' \
              -e 's/CI_NOVA_PASSWORD/${NOVA_PASSWORD}/' \
              ./application/auth.json
      - run:
          name: install dependencies with composer
          command: cd application && composer install --no-dev --classmap-authoritative --no-progress --no-interaction
      - save_cache:
          key: composer-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./cache/composer
      - save_cache:
          key: vendor-{{ checksum "./composer.lock" }}
          paths:
            - ./vendor
