name: Deploy Stage

on:
  push:
    branches:
      - main

jobs:
  stage:
    name: Deploy Stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Yarn install
        uses: borales/actions-yarn@v2.3.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: eu-central-1
     
      - name: Build and push docker image
        run: |
           cd ./infrastructure
           echo "@exporo:registry=https://npm.pkg.github.com/" >> ~/.npmrc
           echo "//npm.pkg.github.com/:_authToken=$NPM_READ_TOKEN" >> ~/.npmrc
           yarn install
           yarn run docker
     
      - name: Update aws infrastructure - reload/restart services
        run: cd ./infrastructure && yarn run aws
