name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          ini-values: max_execution_time=0
      
      - name: Login to Laravel Nova
        run: cd application && composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
        env:
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}

      - name: install dependencies with composer
        run: |
          cd application 
          composer config github-oauth.github.com $COMPOSER_TOKEN
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
#          composer install --no-progress --no-interaction  --no-scripts --no-progress --prefer-dist

        env:
          COMPOSER_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Lint the Project
        run: cd application && composer lint
