name: Test

on:
  push:
    branches-ignore:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: forge
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          ini-values: max_execution_time=0
      
      - name: Login to Laravel Nova
        run: cd application && composer config http-basic.nova.laravel.com ${NOVA_USERNAME} ${NOVA_PASSWORD}
        env:
          NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
          NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}

      - name: install dependencies with composer
        run: cd application && composer install --no-progress --no-interaction
  
      - name: Configure NPM
        run: |
          echo "@exporo:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_READ_TOKEN }}" >> ~/.npmrc

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Yarn install
        run: cd application && yarn install --frozen-lockfile
  
      - name: Build frontend assets
        run: cd application && yarn run production
      
      - name: Run Unit Tests
        run: cd application && DB_PORT=3306 DB_USERNAME=homestead DB_PASSWORD=secret ./vendor/bin/phpunit --log-junit ~/phpunit/junit.xml

      - name: Store Test Results
        uses: actions/upload-artifact@v2
        with:
          name: php-unit results
          path: ~/phpunit

      # todo - what is this for?
      # - name: set nova auth parameter
